collections:
  authors:
    output: true
title: swifting.io - Sharing passion in Swift
description: Blog about development in Swift programming language.
minima:
  social_links:
    github: swiftingio
    twitter: swiftingio
    rss: https://swifting.io/feed/
    email: contact@swifting.io
author:
  email: contact@swifting.io
url: "https://swifting.io"
twitter_username: swiftingio
github_username:  swiftingio
google_analytics: our-GA-key
# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#  - Gemfile
#  - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/